[package]
name = "goodstein_seq"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
easy_io = "0.3.0"
radix_fmt = "1.0.0"